{
 "title": "QA ChatBot",
 "description": "QA Chatbot with LLMs",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Last 5 Questions",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  request_time AS time,\n  question,\n  answer,\n  relevance\nFROM conversation\nWHERE request_time BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY request_time DESC\nLIMIT 5"
    }
   ]
  },
  {
   "title": "Games Requested",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  game,\n  COUNT(*) as count\nFROM conversation \nWHERE request_time BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY game"
    }
   ]
  },
  {
   "title": "Feedback",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(CASE WHEN feedback_score > 0 THEN 1 ELSE 0 END) as thumbs_up,\n  SUM(CASE WHEN feedback_score < 0 THEN 1 ELSE 0 END) as thumbs_down\nFROM feedback\nWHERE feedback_date BETWEEN $__timeFrom() AND $__timeTo()"
    }
   ]
  },
  {
   "title": "Relevance Distribution ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(CASE WHEN relevance = 'RELEVANT' THEN 1 ELSE 0 END) as RELEVANT,\n  SUM(CASE WHEN relevance = 'PARTLY_RELEVANT' THEN 1 ELSE 0 END) as PARTLY_RELEVANT,\n  SUM(CASE WHEN relevance = 'NON_RELEVANT' THEN 1 ELSE 0 END) as NON_RELEVANT\nFROM conversation\nWHERE request_time BETWEEN $__timeFrom() AND $__timeTo()\n"
    }
   ]
  },
  {
   "title": "Model Cost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(request_time, $__interval) AS time,\n  SUM(model_cost) AS total_cost\nFROM conversation \nWHERE request_time BETWEEN $__timeFrom() AND $__timeTo()\n  AND model_cost > 0\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Models Usage",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  model,\n  COUNT(*) as count\nFROM conversation \nWHERE request_time BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY model"
    }
   ]
  },
  {
   "title": "Avg Tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(request_time, $__interval) AS time,\n  AVG(total_tokens) AS avg_tokens\nFROM conversation \nWHERE request_time BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  request_time AS time,\n  response_time\nFROM conversation \nWHERE request_time BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY request_time"
    }
   ]
  }
 ]
}